### ISSUE TITLE
HorizontalOffset still not working

### ISSUE THREAD

**Issue by Thuuna** [mpstark/DynamicCam#110]
Hello,

I just updated Dynamiccam to the newest Version but the HorizontalOffset in Situations and in global still not working. (Patch 11.0.2) (It worked at Patch 11.0.0)

I changed the parameter but the camera stays in the middle.

![Screenshot 2024-08-14 182000](https://github.com/user-attachments/assets/20fc3a2d-ce77-4f1e-9b89-59b2d0c5a395)

**Comment by FrancisMT** [comment]
Same issue. Using DynamicCam version 2.8.2.

**Comment by Thuuna** [comment]
Parameter is -2.2 but character stays in the middle.

![Screenshot 2024-08-14 182656](https://github.com/user-attachments/assets/60bbd524-612c-4899-aabb-67e1d90082a2)

**Comment by Thuuna** [comment]
Dynamiccam Version 2.8.3 -> No changes to HorizontalOffset problem.

**Comment by LudiusMaximus** [comment]
Right! I think it has to do with the game's "Motion Sickness" option. DynamicCam used to automatically disable this, which seems to be broken since 11.0.2. For the time being, just disable Motion Sickness manually. I will enforce it again with the next release.

**Comment by FrancisMT** [comment]
That solves it. Thank you @LudiusMaximus

**Comment by Thuuna** [comment]
Worked. :) Thank you so much for the quick workaround. @LudiusMaximus

**Comment by LudiusMaximus** [comment]
Bizarrely, since 11.0.2 checking the "Motion Sickness" checkbox sets
CameraKeepCharacterCentered = false  and  CameraReduceUnexpectedMovement = true
whereas unchecking the checkbox sets
CameraKeepCharacterCentered = true  and  CameraReduceUnexpectedMovement = false
Either variable being true stops shoulder offset from taking effect, so I disabled the checkbox completely in the latest release 2.8.5.

Thanks again for your support!
