### ISSUE TITLE
Shoulder offset OR Motion Sickness

### ISSUE THREAD

**Issue by gizzmo** [mpstark/DynamicCam#111]
Please make it a choice. Either by disabling the motion sickness when ever the shoulder offset is set to something that is not 0, or by having an option. 

I have never felt more disoriented and nauseous then the first second after flying after this update. I only have one rarely used situation that uses a shoulder offset, and I'd rather give that up than having to feel sick whenever I fly.

**Comment by LudiusMaximus** [comment]
I hear you. What's really strange since 11.0.2 is that the internal cvar "CameraReduceUnexpectedMovement" (which is enabled by checking the "Motion Sickness" box) also prevents the shoulder offset from taking effect. Before, it was only the internal variable "CameraKeepCharacterCentered", which is now strangely enabled by **un**checking the "Motion Sickness" box... So I had to also disable CameraReduceUnexpectedMovement, but I will make it such with the next release that this will only happen when the shoulder offset is different from 0.

**Comment by gizzmo** [comment]
Thank you. And I can understand having to do things to work around weird Blizzard bugs.

**Comment by LudiusMaximus** [comment]
With DynamicCam 2.8.6 we are only disabling the Motion Sickness setting while horizontal or vertical camera offset is used. At least these are the only camera settings I found to be affected (justified or not) by the Motion Sickness setting so far.
