### ISSUE TITLE
Can't have a frame name. Can you help me?

### ISSUE THREAD

**Issue by Maravelll** [mpstark/DynamicCam#115]
Hello everyone!

Again, your mods is one of the best i have used. I really enjoy configurates every single part in the game for a better immersive experience. So thakyou! But I have three question I want to present to you. This is the first (the others will be in difrent post).

Well, as in the title, I can't have the name of a frame. The frame in question is the little windows that appears when you learn a new recipe or a new fish in your fishing book. I try all the ways, even changing the "cortex" with alt button but without success.

Can you assistme whith this particular frame name, please? 

I'll let this picture. Hope it helps.

See you! 

![WoWScrnShot_083024_101110](https://github.com/user-attachments/assets/c25c5b5c-3fb2-4a08-8f4f-6b0370dab317)

**Comment by LudiusMaximus** [comment]
Hi and sorry for the late reply!

These pop-ups are tricky, because they are generated by the game when used. So there is no unique name to identify them. In one of my other addons (Immersion ExtraFade), I took the effort to catch them at the moment they are created so I could hide them during NPC interaction.

What do you have in mind with them?
