### ISSUE TITLE
Cannot import or export files

### ISSUE THREAD

**Issue by oddestduckling** [mpstark/DynamicCam#80]
I used this addon years ago and I know that it was super robust, and also functioned more or less out of the box.

When I downloaded it today, however, apparently import/export features are "coming soon" and none of the profiles have any changes applied to them? I can understand the latter, but have import/export features become disabled for some reason? I can find absolutely no one having this problem anywhere I look

**Comment by LudiusMaximus** [comment]
Hello, the DynamicCam situations have undergone a complete overhaul which is why the import/export still needs to undergo the same transformation. Sorry for that.

**Comment by ccrowles** [comment]
It's been almost a year since this feature has been removed, do you still have plans to re-implement it eventually?

**Comment by LudiusMaximus** [comment]
Yeah, I can understand your frustration. Re-working the profile import/export and presets is just such a big chunk of coding, that I have never seen a time window in which I would be able to tackle it. I know that it is most wanted by lots of DynamicCam users, but my real-life (kids, family and job) only leave me very little time for my hobby.

**Comment by ccrowles** [comment]
That's ok, I didn't mean to pressure you, sorry if it seemed that way. I was just asking in order to understand if I should install the addon and try to figure it out myself, or wait for the import feature to be readded and use Kraken Latte's import string for it.
I completely understand real life having priority over everything, especially with so much on your plate. Best of luck!
