### ISSUE TITLE
is dynamic cam working as of 11.0?

### ISSUE THREAD

**Issue by zeebea** [mpstark/DynamicCam#99]
im trying to edit the set zoom settings for dragonriding and it seems like nothing is working- ive tried editing the mounted, dracthyr soar, and both dragonriding zoom settings and it's not changing anything at all

not sure if its my end or if theres some issues with the newest patch
just wanted to check

**Comment by Azsheraax** [comment]
I have the same problem with the dracthyr soar. 
I thought maybe we have to precise in Situation Controls > Events the unit_aura implied. I found what seems to be a synthax (UNIT_AURA: unitTarget, updateInfo) on this page https://warcraft.wiki.gg/wiki/UNIT_AURA. unitTarget should be player I assume, but I'm not a coder, I was a little discouraged given there may be several instructions needed in Initialization or Condition as well...

**Comment by LudiusMaximus** [comment]
Thanks a lot for bringing this to my attention! They changed the buff ID for dracthyr soar. And since skyriding has become the default, some changed had to be made to detect it. I just released the new version, in which this has been fixed. (https://github.com/Mpstark/DynamicCam/compare/2.7.1...2.7.2).

**Comment by Azsheraax** [comment]
Hurray \o/ Thank you so much \o/
